blog:
    resource: "@BLOGBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:   ['%http_protocol%']

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    schemes:   ['%http_protocol%']

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    schemes:   ['%http_protocol%']

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    schemes:   ['%http_protocol%']