# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.image_uploader:
        class: BLOGBundle\FileUploader
        arguments: ['%image_directory%']
