<?php

namespace BLOGBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
//
//    public function myFindCat($category)
//    {
//        $qb = $this->createQueryBuilder('category');
//
//        $qb->where('category.category = :category')->setParameter('category', $category);
//
//        return $qb->getQuery()->getResult();
//    }
}
