<?php

namespace BLOGBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll(){
        $qb = $this->createQueryBuilder('comments');
        $qb->where('comments.publication = :publication')
            ->setParameter('publication', '0');
        return $qb->getQuery()->getResult();
    }

}
