<?php

namespace BLOGBundle\Repository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindLast($id){
        $qb = $this->createQueryBuilder('i')
            ->where('i.id > :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
