<?php

namespace BLOGBundle\Repository;

/**
 * PresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentationRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFindOne(){
        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->setMaxResults(1);
    return $qb->getQuery()->getOneOrNullResult();
    }


}
