user:
    resource: "@BLOGBundle/Resources/config/routing/user.yml"
    prefix:   /{_locale}
    requirements: 
        _locale: fr|es|
                         
admin:
    resource: "@BLOGBundle/Resources/config/routing/admin.yml"
    prefix:   /admin