admin_index:
    path:     /
    defaults: { _controller: "BLOGBundle:Admin:index" }

admin_add:
    path:     /add
    defaults: { _controller: "BLOGBundle:Admin:add" }
    methods:  [GET, POST]

admin_edit:
    path:     /edit/{id}
    defaults: { _controller: "BLOGBundle:Admin:edit" }
    methods:  [GET, POST]

admin_delete:
    path:     /delete/{id}
    defaults: { _controller: "BLOGBundle:Admin:delete" }

admin_profil:
    path:     /profil
    defaults: { _controller: "BLOGBundle:Admin:profil" }

admin_profil_edit:
    path:     /profil/edit
    defaults: { _controller: "BLOGBundle:Admin:profilEdit" }

admin_comments:
    path:     /comments
    defaults: { _controller: "BLOGBundle:Admin:comment" }

admin_comments_validation:
    path:     /comments/{id}
    defaults: { _controller: "BLOGBundle:Admin:commentValidation" }

admin_comments_unvalidation:
    path:     /commentsHide/{id}
    defaults: { _controller: "BLOGBundle:Admin:commentUnvalidation" }
    
admin_comments_delete:
    path:     /comments/delete/{id}
    defaults: { _controller: "BLOGBundle:Admin:commentDelete" }    

admin_newsletter:
    path:     /newsletter
    defaults: { _controller: "BLOGBundle:Admin:newsletter" }