admin_index:
    path:     /
    defaults: { _controller: "BLOGBundle:Article:index" }
    methods:  GET

admin_show:
    path:     /{id}/show
    defaults: { _controller: "BLOGBundle:Article:show" }
    methods:  GET

admin_new:
    path:     /new
    defaults: { _controller: "BLOGBundle:Article:new" }
    methods:  [GET, POST]

admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "BLOGBundle:Article:edit" }
    methods:  [GET, POST]

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "BLOGBundle:Article:delete" }
    methods:  DELETE
