BLOGBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: BLOGBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        date:
            type: date

    manyToMany:
        category:
            targetEntity: BLOGBundle\Entity\Category
            mappedBy: article
            cascade: ["persist"]
            

    oneToMany:
        image:
            targetEntity: BLOGBundle\Entity\Image
            mappedBy: article

    oneToMany:
        comment:
            target: BLOGBundle\Entity\Comments
            mappedBy: article

  


