BLOGBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: BLOGBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titleFr:
            type: string
            length: 255
        titleEs:
            type: string
            length: 255
        date:
            type: datetime
        newsletter:
            type: boolean
        longitude:
            type: float
        latitude:
            type: float
    manyToMany:
        category:
            targetEntity: BLOGBundle\Entity\Category
            mappedBy: article
            cascade: ["persist"]

    oneToMany:
        image:
            targetEntity: BLOGBundle\Entity\Image
            mappedBy: article
            cascade: ["persist","remove"]
        comment:
            targetEntity: BLOGBundle\Entity\Comments
            mappedBy: article
            cascade: ["persist","remove"]
        content:
            targetEntity: BLOGBundle\Entity\Content
            mappedBy: article
            cascade: ["persist","remove"]


  


