BLOGBundle\Entity\NewsLetter:
    type: entity
    table: null
    repositoryClass: BLOGBundle\Repository\NewsLetterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        lien:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
